### ISSUE TITLE
problem on Ubuntu 20.04

### ISSUE THREAD

**Issue by serdar-sahin** [MikeCodesDotNET/Avalonia-QRCode#2]
Hi, firstly thank you for this nice job.

Ubuntu gives the following message when I add and run the project.
Avalonia ui is working, but qrcode is not showing.
A white blank window appears. 

Tmds.DBus.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.canonical.AppMenu.Registrar was not provided by any .service files
   at Tmds.DBus.DBusConnection.CallMethodAsync(Message msg, Boolean checkConnected, Boolean checkReplyType)
   at Tmds.DBus.Connection.CallMethodAsync(Message message)
   at Tmds.DBus.CodeGen.DBusObjectProxy.SendMethodReturnReaderAsync(String iface, String member, Nullable`1 inSignature, MessageWriter writer)
   at Avalonia.FreeDesktop.DBusMenuExporter.DBusMenuExporterImpl.Init() in /_/src/Avalonia.FreeDesktop/DBusMenuExporter.cs:line 59
Tmds.DBus.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.canonical.AppMenu.Registrar was not provided by any .service files
   at Tmds.DBus.DBusConnection.CallMethodAsync(Message msg, Boolean checkConnected, Boolean checkReplyType)
   at Tmds.DBus.Connection.CallMethodAsync(Message message)
   at Tmds.DBus.CodeGen.DBusObjectProxy.SendMethodReturnReaderAsync(String iface, String member, Nullable`1 inSignature, MessageWriter writer)
   at Avalonia.FreeDesktop.DBusMenuExporter.DBusMenuExporterImpl.Init() in /_/src/Avalonia.FreeDesktop/DBusMenuExporter.cs:line 59

**Comment by serdar-sahin** [comment]
dbus error fixed this way;
.With(new X11PlatformOptions { UseDBusMenu = false })

but the qrcode white blank window issue still persists.

**Comment by serdar-sahin** [comment]
the problem is solved in this way. 

apt-get install libgdiplus
cd /usr/lib
ln -s libgdiplus.so gdiplus.dll
